### ISSUE TITLE
Tratamento de Login

### ISSUE THREAD

**Issue by FranzFialho** [bgmulinari/B1SLayer#12]
Bom dia!

Como seria feito o tratamento do Login, sendo que a duração de cada Login dura 30 minutos.

Como eu verificaria se estaria conectado ou se preciso realizar um novo login.

**Comment by bgmulinari** [comment]
Bom dia, @FranzFialho.

Com o B1SLayer o login e o gerenciamento de sessão é automático, você não precisa fazer nada. Desde que você mantenha seu objeto `SLConnection` vivo em sua aplicação, ou seja, instancia-lo uma única vez e reutiliza-lo, ele efetuará o login e a renovação da sessão automaticamente sempre que necessário.

Recomendo a leitura do meu post na comunidade SAP para mais detalhes sobre o funcionamento da biblioteca: https://blogs.sap.com/2022/05/23/b1slayer-a-clean-and-easy-way-to-consume-sap-business-one-service-layer-with-.net/

**Comment by bgmulinari** [comment]
Estou fechando a issue. Caso ainda tenha alguma dúvida, sinta-se à vontade para reabri-la.
