### ISSUE TITLE
return values for Patch-methods?

### ISSUE THREAD

**Issue by sofdwere** [bgmulinari/B1SLayer#15]
As SAP Service Layer User Manual says, the using of PATCH or PUT to update an entity returns HTTP code 204:

> On success, HTTP code 204 is returned without content.

Does it make sense to return something so it is possible to check for this code?
For example and testing I have returned the _FlurlResponse_:

using:

```C#
Flurl.Http.FlurlResponse ret = null;
try {
    ret = await serviceLayer.Request("Items", "124").PatchStringAsync("{\"ItemName\": \"xxx\"}");
}
catch {}
if (ret != null && ret.StatusCode == 204) {
    Application.SBO_Application.MessageBox("Success.");
}
```

code change:

```C#
public async Task<Flurl.Http.FlurlResponse> PatchStringAsync(string data)
{
    Flurl.Http.FlurlResponse response = null;
    await _slConnection.ExecuteRequest(async () =>
    {
        response = (FlurlResponse)await FlurlRequest.WithCookies(_slConnection.Cookies).PatchStringAsync(data);
        return response;
    });
    return response;
}
```

**Comment by bgmulinari** [comment]
Hi, @sofdwere. The default behaviour in B1SLayer that is inherited from Flurl is that every unsuccessful request, that is, with non 2xx HTTP code, will throw an Exception. So there is no need to check the status code like you are showing here; if you request didn't throw, it was successful.

As PATCH, PUT or DELETE requests to Service Layer don't return any content, I didn't see a reason for these methods to have a return type. The `IFlurlResponse` object wouldn't have much use besides the status code, which is already taken into consideration as I mentioned above.

**Comment by sofdwere** [comment]
At least for better feeling =)
What about the other 2xx codes except 204? SAP manual mentions only 204 for success, but what if I want to notice other 2xx codes like 200 and so on. Perhaps the could also signify an error or something, I expect everything of SAP ^^ :-D

**Comment by bgmulinari** [comment]
Like I said, if the response code is in the 200-299 range (2xx), it was successful. 200, 201, 204, are all successful codes that Service Layer respects. This is an [HTTP standard](https://datatracker.ietf.org/doc/html/rfc7231#section-6) that [Flurl implements](https://flurl.dev/docs/error-handling/#error-handling).

For instance, for a POST request the code is usually 201 (Created). For a PATCH, 204 (No Content). Both successful.

So, your code snippet could be rewritten as simple as this:

````c#
try 
{
    await serviceLayer.Request("Items", "124").PatchStringAsync(new { ItemName = "xxx" });
    Application.SBO_Application.MessageBox("Success.");
}
catch (Exception ex)
{
    Application.SBO_Application.MessageBox("Something went wrong: " + ex.Message);
}
````
