### ISSUE TITLE
error handling in batch processing

### ISSUE THREAD

**Issue by sofdwere** [bgmulinari/B1SLayer#16]
Are these statements correct?

- `PostBatchAsync()` respectively `Flurl.Http.MultipartExtensions.PostMultipartAsync` does never throw an exception like `SLException` or `FlurlHttpException` for logic errors from B1 (like '256000267 - The unit of length, width, height or weight cannot be set if the length, width, height or weight is 0.').
- Batch processing in `PostBatchAsync()` respectively `Flurl.Http.MultipartExtensions.PostMultipartAsync` stops on request with error (for example statuscode 400), so if  `PostBatchAsync()` is executed with a list of 3 requests and the 2nd produces an error (with for example statuscode 400), the 3rd request will not be executed and it returns a batchResult with only 2 entries (for example statuscodes 204 and 400).
- Therefore this will be an exemple for an appropriate error handling:
```C#
List<SLBatchRequest> slBatchRequests = new List<SLBatchRequest>();
slBatchRequests.Add(new SLBatchRequest(new System.Net.Http.HttpMethod("PATCH"), "Items('123')", new {ItemName = "xxx"}));
slBatchRequests.Add(new SLBatchRequest(new System.Net.Http.HttpMethod("PATCH"), "Items('124')", new {ItemName = "xxx"})); //item with error
slBatchRequests.Add(new SLBatchRequest(new System.Net.Http.HttpMethod("PATCH"), "Items('125')", new {ItemName = "xxx"}));
const string jsonContentType = "application/json";
System.Net.Http.HttpResponseMessage[] batchResult = null;
batchResult = await serviceLayer.PostBatchAsync(slBatchRequests, false);
for (int i = 0; i < batchResult.Length; i++) {
    if (!batchResult[i].IsSuccessStatusCode) {
        if (batchResult[i].Content != null && batchResult[i].Content.Headers.ContentType.MediaType == jsonContentType) {
            string jsonString = await batchResult[i].Content.ReadAsStringAsync();
            SLResponseError error = JsonConvert.DeserializeObject<SLResponseError>(jsonString);
            Console.WriteLine($"Error in request {i + 1}: {error.Error.Code}, {error.Error.Message.Value}");
        }
        else {
            Console.WriteLine($"Error in request {i + 1}: unknown error");
        }
    }
}
if(batchResult.Count() < slBatchRequests.Count) {
    Console.WriteLine($"Due to error in request {batchResult.Count()} the following {slBatchRequests.Count - batchResult.Count()} requests have not been executed.");    
}
```

**Comment by sofdwere** [comment]
In my usecase each request is the update of one item-pricelist-price and the addon has to change/import as much as possible. The user should only take care of the data sets which could not been imported successfully, so in my opinion singleChangeSet=false is correct.
Thank you for your comment.

**Comment by thiagobarrosrj** [comment]
Boa tarde. Gostaria de aproveitar este tópico.

Eu entendi que singleChangeSet=false, ele irá parar ao primeiro erro e não prosseguirá com as requisições, certo?

Mas tem alguma forma de ele processar o máximo possível?

Ou seja, se eu mandar 50 requisições, apenas a 27º tiver com problema, mesmo assim ele seguir e processar as demais?

Pois pelos testes que fiz não consegui esse comportamento.
