### ISSUE TITLE
Example for request with composite primary key

### ISSUE THREAD

**Issue by sofdwere** [bgmulinari/B1SLayer#17]
Perhaps it would be nice to have such an example in the [README.md](https://github.com/bgmulinari/B1SLayer#readme):

```C#
serviceLayer.Request("AlternateCatNum(ItemCode='123',CardCode='456',Substitute='789')").PatchAsync(new { DisplayBPCatalogNumber = "tYES" });
```

**Comment by bgmulinari** [comment]
Hi, @sofdwere. The [README.md](https://github.com/bgmulinari/B1SLayer#readme) was updated with the suggested example.
