### ISSUE TITLE
Cant upload multiple attachments in a single request?

### ISSUE THREAD

**Issue by josue30iso** [bgmulinari/B1SLayer#19]
I needed some way to make multiple file upload to obtain a single attachment entry... It's this actually possible?

**Comment by bgmulinari** [comment]
Hi, @josue30iso. Currently this is not possible, but I'll be adding support for it in the upcoming version.

**Comment by bgmulinari** [comment]
Hi, @josue30iso.

I'm sorry for the delay on this, but I was mistaken on my previous answer. Uploading multiple files to a single attachment entry is already possible through the method `PostAttachmentsAsync`, where you use a `Dictionary` to specify the files you want to upload. If you have any doubts, please let me know.
