### ISSUE TITLE
Multiple File Attachment Issue

### ISSUE THREAD

**Issue by rahuljain257** [bgmulinari/B1SLayer#2]
Hello bgMulinari,

Greetings, Thanks for creating this wonderful library 👍 I am trying to use it in my project. We have the requirement to upload multiple files @ one go. So I was trying to put my hands-on the following methods but stumbling upon the following error -

I tried using all the methods but its failed

Method 1 - PostAttachmentsAsync --(fileName, byteArray)
Method 2 - PostAttachmentsAsync -- (fileName, Stream) 

**Screen-Shot 1** 

![image](https://user-images.githubusercontent.com/948834/143674704-b8cc925c-3282-41d7-9093-6b4ee625e84e.png)

Screen-Shot 2

![image](https://user-images.githubusercontent.com/948834/143674745-8e0edf44-6645-426e-8b66-ba5af49bd938.png)

I also tried to upload the single file using the following method - 

`var attachmentEntry = await serviceLayer.PostAttachmentAsync(@"C:\files\myfile.pdf");` and it worked.

Also if possible Can you please share sample code of uploading multiple files  because for me its getting failed :(

**Comment by bgmulinari** [comment]
Hi, Rahul. I see you closed your issue. Were you able to solve the issue? Let me know if I can help.

**Comment by rahuljain257** [comment]
Yes, I was able to fix the issue. It was logical issue.
