### ISSUE TITLE
Multiple filters in .Filter method

### ISSUE THREAD

**Issue by nickitatkach** [bgmulinari/B1SLayer#20]
Hello,

I would like to know how add multiple filter in a single request such as startswith and eq.
For instance, .Filter("Disabled eq 'N'", "startswith(CardName, 'C')").

Thank you.

**Comment by bgmulinari** [comment]
Hello, @nickitatkach.

You can already do this by using the standard Service Layer's logical and relational operators. [Check the Service Layer User Manual for more details on this.](https://help.sap.com/doc/6ab840ef2e8140f3af9eeb7d8fef9f06/10.0/en-US/Working_with_SAP_Business_One_Service_Layer.pdf#page=33)

In your example, it should be like this:
`
.Filter("Disabled eq 'N' and startswith(CardName, 'C')")
`

**Comment by nickitatkach** [comment]
Hello @bgmulinari,

Thank you very much, it works!
