### ISSUE TITLE
B1S-ReplaceCollectionsOnPatch in true

### ISSUE THREAD

**Issue by mruiz-GIEG** [bgmulinari/B1SLayer#25]
Good evening, how can I enable the B1S-ReplaceCollectionsOnPatch to true to execute the PatchStringAsync to be able to add banks in the business partners, in postman it works fine for me with this structure but with the ReplaceCollectionsOnPatch to true

{
             "BPBankAccounts": [{
                 "InternalKey": 94,
                 "Country": "NOR",
                 "BankCode": "BDF",
                 "AccountNo": "35451111",
                 "IBAN": "USD"
             },
             {
                 "InternalKey": 95,
                 "Country": "NOR",
                 "BankCode": "BANPRO",
                 "AccountNo": "232323",
                 "IBAN": "USD"

             }]
}

**Comment by mruiz-GIEG** [comment]
https://1.1.0.1:50000/b1s/v1/BusinessPartners('PN001498')

add headers B1S-ReplaceCollectionsOnPatch=true

**Comment by bgmulinari** [comment]
Hi, @mruiz-GIEG.

You can simply configure your request with the extension method `WithReplaceCollectionsOnPatch()`.

**Comment by mruiz-GIEG** [comment]
> Hola,@mruiz-GIEG.
> 
> Simplemente puede configurar su solicitud con el método de extensión `WithReplaceCollectionsOnPatch()`.

Thank you very much excellent work
