### ISSUE TITLE
SAP Service Layer - Login Response

### ISSUE THREAD

**Issue by rahuljain257** [bgmulinari/B1SLayer#3]
Hello Mate,

I tried to Login using the following method - 
`var serviceLayer = new SLConnection("https://sapserver:50000/b1s/v1", "CompanyDB", "manager", "12345");`

but how to fetch the session ID ? because I am getting complete object as NULL. Please find the below screenshot for your reference

![image](https://user-images.githubusercontent.com/948834/143683392-e533b4cc-d487-440e-8829-7a813eede90b.png)

regards
Rahul Jain

**Comment by bgmulinari** [comment]
Hi, Rahul. B1SLayer manages the session for you, that means the login is performed automatically before the first request to Service Layer, you don't have to do anything. In your case, you just created the SLConnection instance and you won't have an active session until a request is performed.

If for some reason you need the session before any request is performed, you can manually call the LoginAsync method, but generally this is not necessary.

**Comment by rahuljain257** [comment]
Thanks 👍
