### ISSUE TITLE
Patch Address in BusinessPartners

### ISSUE THREAD

**Issue by JorgeNT1981** [bgmulinari/B1SLayer#30]
Good morning, I'm having trouble when I want to patch Address in BusinessParterns, here some code:

In Postman works, modified the rowNum (0) :

BusinessPartners(CardCode = 'C1801123')
{
            "BPAddresses": [
                {
                    "RowNum": 0,
                    "AddressName": "Bill To",
                    "Street": "calle 4665",
                    "Country": "BO",
                    "FederalTaxID": "34343434",
                    "TaxCode": "IVA_ICE",
                    "AddressType": "bo_BillTo",
                    "AddressName2": "Test",
                    "AddressName3": "Test",
                    "BPCode": "C1801123"
                }
            ]
}

but whit this code, create another RowNum:

var Direcciones = new
                {
                    CardName = bp.CardName,
                    BPAddresses = new List<object>()
                    {
                        new {
                            RowNum = 0,
                            AddressName = "Bill To",
                            AddressName2 = "test",
                            AddressName3 = "test",
                            Street = "",
                            TaxCode = "IVA",
                            Country = "BO",
                            StreetNo = "test",
                            FederalTaxID = "test"
                        }
                    }
                };
                await _serviceLayerConn
                    .Request($"BusinessPartners(CardCode = '{bp.CardCode}')")
                    .PatchAsync(Direcciones);

Any Ideas?

**Comment by bgmulinari** [comment]
Hi, @JorgeNT1981. Can you provide more details on your problem?

Usually for patching collections you need to pass the `B1S-ReplaceCollectionsOnPatch=true` header on the request. This can be done in B1SLayer through the `WithReplaceCollectionsOnPatch` extension method.

**Comment by JorgeNT1981** [comment]
Thank you @bgmulinari for the quick response. I used WithReplaceCollectionsOnPatch  and it worked fine.
