### ISSUE TITLE
Login request with 30+ seconds response time

### ISSUE THREAD

**Issue by it-AhmedTaha** [bgmulinari/B1SLayer#31]
Hi, I am trying to verify user credentials doing this  

`  await _serviceLayer.Request("Login").PostAsync(new SapLogin
        {
            CompanyDB = _configuration["Sap:DatabaseName"],
            Password = request.Password,
            UserName = request.Username
        });`
        
When user credentials  are correct I get response in 3-8 seconds, however when the credentials are wrong response time is between 30-40 seconds. Am I doing anything wrong?

I was using normal http request and maximum time normally would be 6 seconds.

**Comment by it-AhmedTaha** [comment]
I've just realized that this isn't a problem. The default number of attempts is three, which results in a long response time.

**Comment by it-AhmedTaha** [comment]
Before I close this issue, is it possible to do a request without setting cookies or checking for active session?

**Comment by bgmulinari** [comment]
Hi, @it-AhmedTaha.

I see that you are trying to perform a login request, this isn't necessary as B1SLayer does that automatically.

I recommend you reading my blog post on SAP Community: https://blogs.sap.com/2022/05/23/b1slayer-a-clean-and-easy-way-to-consume-sap-business-one-service-layer-with-.net/

**Comment by it-AhmedTaha** [comment]
I understand that the B1SLayer application provides automatic handling of login and session.
In my company, certain SAP users do not possess licenses, and therefore, we utilize a single licensed user to perform tasks and actions. 
Prior to granting access to users without licenses, it is necessary for me to verify the user credentials. 
Hence, I am wondering whether it is possible to perform this verification (login request) without setting cookies or checking for active session?

Right now I am doing this  
`await _serviceLayer.Request("Login").PostAsync(new SapLogin 
{ CompanyDB = _configuration["Sap:DatabaseName"], 
Password = request.Password, 
UserName = request.Username });
`
it is working fine, but the if there is no session or the session has expired B1SLayer will automatically fire a request with the default licensed user to get a new session which will results in longer response time.

**Comment by bgmulinari** [comment]
Hi, @it-AhmedTaha.

Performing a POST to the Login resource manually like you're doing is not going to set or replace the existing session that B1SLayer manages automatically.

**Comment by it-AhmedTaha** [comment]
Hi again, 
I am registering the SLConnection instance as a singleton and setting the number NumberOfAttempts to 1 like this 
```
builder.Services.AddSingleton(_=> new SLConnection(
        $"https://{builder.Configuration["Sap:ServiceLayerBase"]}",
        builder.Configuration["Sap:DatabaseName"],
        builder.Configuration["Sap:Username"],
        builder.Configuration["Sap:Password"])
    {
        NumberOfAttempts = 1
    });
```
Some time I get this error "invalid session" , so I have to resend the request again. 
Is this happing because I am setting NumberOfAttempts to 1?

**Comment by bgmulinari** [comment]
I think it could be related, yes. I'll try to investigate this further, but for now setting `NumberOfAttempts = 2` should prevent this.

Thanks for bringing this up.

**Comment by it-AhmedTaha** [comment]
> I think it could be related, yes. I'll try to investigate this further, but for now setting `NumberOfAttempts = 2` should prevent this.
> 
Thank you.
I will be waiting for your update or fix on the issue

**Comment by it-AhmedTaha** [comment]
Hi, Thank you for the new update. I did some tests and I still get "invalid session".
