### ISSUE TITLE
inlinecount 

### ISSUE THREAD

**Issue by WitmondPaul** [bgmulinari/B1SLayer#33]
Hi Bruno,

Is it possible to add the inlinecount to the request ?

example :
https://api.demoserver:50000/b1s/v2/Users?$select=UserCode,UserName&$inlinecount=allpages

result from Postman :
![image](https://user-images.githubusercontent.com/118984124/230408461-1dc0b2d8-c338-4558-b448-d61c7b2b1534.png)

In Postman it's working fine.

I know you have GetCountAsync() but I don't want to make 2 call's when only 1 is enough

**Comment by bgmulinari** [comment]
Hi, @WitmondPaul.

Thanks for your suggestion. I'll evaluate how to implement this feature for the next release.

**Comment by bgmulinari** [comment]
Hi, @WitmondPaul.

I just pushed a commit to the dev branch that adds a new request method called `GetWithInlineCountAsync()`. It returns a value tuple containing the result and the count.

If you are able to test it, please let me know if it works for you.

**Comment by WitmondPaul** [comment]
Hi Bruno,

How do I get the new version ?
On Github it’s still 1.3.0

Best regards / Met vriendelijke groet,

Paul Witmond


Planlogic B.V. | Bolderweg 2 | 1332 AT  Almere | T. +31 (0)36 3030003| M. +31 (0)627 096 016| KvK 11033102
***@***.***
Volg ons online: www.planlogic.nl<http://www.planlogic.nl/> | LinkedIn<https://www.linkedin.com/company/planlogic-b-v-> | Facebook<https://www.facebook.com/PlanlogicNederland/>

The contents of this message, as well as any enclosures, are addressed personally to, and thus solely intended for the addressee. They may contain information regarding a third party. Any recipient who is neither the addressee, nor empowered to receive this message on behalf of the addressee, is kindly requested to immediately inform the sender of receipt. Any use of the contents of this message and/or of the enclosures by any other person than the addressee is illegal towards the sender and the aforementioned third party. Always scan attachments before opening them.


Van: Bruno Mulinari ***@***.***>
Verzonden: donderdag 13 april 2023 17:39
Aan: bgmulinari/B1SLayer ***@***.***>
CC: Paul Witmond | Planlogic ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [bgmulinari/B1SLayer] inlinecount (Issue #33)


Hi, @WitmondPaul<https://github.com/WitmondPaul>.

I just pushed a commit to the dev branch that adds a new request method called GetWithInlineCountAsync(). It returns a value tuple containing the result and the count.

If you are able to test it, please let me know if it works for you.

**Comment by bgmulinari** [comment]
Hi, @WitmondPaul. You can try installing the package directly from the file below:

[B1SLayer.1.3.1.nupkg.zip](https://github.com/bgmulinari/B1SLayer/files/11232993/B1SLayer.1.3.1.nupkg.zip)

**Comment by WitmondPaul** [comment]
Hi Bruno,

I’ve installed the new version.
Can you please provide an example how to use the new function ?

Best regards / Met vriendelijke groet,

Paul Witmond


Planlogic B.V. | Bolderweg 2 | 1332 AT  Almere | T. +31 (0)36 3030003| M. +31 (0)627 096 016| KvK 11033102
***@***.***
Volg ons online: www.planlogic.nl<http://www.planlogic.nl/> | LinkedIn<https://www.linkedin.com/company/planlogic-b-v-> | Facebook<https://www.facebook.com/PlanlogicNederland/>

The contents of this message, as well as any enclosures, are addressed personally to, and thus solely intended for the addressee. They may contain information regarding a third party. Any recipient who is neither the addressee, nor empowered to receive this message on behalf of the addressee, is kindly requested to immediately inform the sender of receipt. Any use of the contents of this message and/or of the enclosures by any other person than the addressee is illegal towards the sender and the aforementioned third party. Always scan attachments before opening them.


Van: Bruno Mulinari ***@***.***>
Verzonden: vrijdag 14 april 2023 14:55
Aan: bgmulinari/B1SLayer ***@***.***>
CC: Paul Witmond | Planlogic ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [bgmulinari/B1SLayer] inlinecount (Issue #33)


Hi, @WitmondPaul<https://github.com/WitmondPaul>. You can try installing the package directly from the file below:

B1SLayer.1.3.1.nupkg.zip<https://github.com/bgmulinari/B1SLayer/files/11232993/B1SLayer.1.3.1.nupkg.zip>

**Comment by bgmulinari** [comment]
Hi, @WitmondPaul. Here's an example:

```c#
var items = await serviceLayer.Request("Items").GetWithInlineCountAsync<List<Item>>();

Console.WriteLine($"There are {items.Count} in total");
Console.WriteLine("Items in the first page:");

foreach (var item in items.Result)
{
    Console.WriteLine(item.ItemCode);
}
```

**Comment by WitmondPaul** [comment]
😊

Best regards / Met vriendelijke groet,

Paul Witmond


Planlogic B.V. | Bolderweg 2 | 1332 AT  Almere | T. +31 (0)36 3030003| M. +31 (0)627 096 016| KvK 11033102
***@***.***
Volg ons online: www.planlogic.nl<http://www.planlogic.nl/> | LinkedIn<https://www.linkedin.com/company/planlogic-b-v-> | Facebook<https://www.facebook.com/PlanlogicNederland/>

The contents of this message, as well as any enclosures, are addressed personally to, and thus solely intended for the addressee. They may contain information regarding a third party. Any recipient who is neither the addressee, nor empowered to receive this message on behalf of the addressee, is kindly requested to immediately inform the sender of receipt. Any use of the contents of this message and/or of the enclosures by any other person than the addressee is illegal towards the sender and the aforementioned third party. Always scan attachments before opening them.


Van: Bruno Mulinari ***@***.***>
Verzonden: maandag 17 april 2023 15:55
Aan: bgmulinari/B1SLayer ***@***.***>
CC: Paul Witmond | Planlogic ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [bgmulinari/B1SLayer] inlinecount (Issue #33)


Hi, @WitmondPaul<https://github.com/WitmondPaul>. Here's an example:

var items = await serviceLayer.Request("Items").GetWithInlineCountAsync<List<Item>>();



Console.WriteLine($"There are {items.Count} in total");

Console.WriteLine("Items in the first page:");



foreach (var item in items.Result)

{

    Console.WriteLine(item.ItemCode);

}

**Comment by bgmulinari** [comment]
Hi, @WitmondPaul. Were you able to test the new method? If so, please let me know.

**Comment by bgmulinari** [comment]
This feature was added in version [1.3.1](https://github.com/bgmulinari/B1SLayer/releases/tag/1.3.1).

Thanks for your suggestion, @WitmondPaul.
