### ISSUE TITLE
How can I cancel a sales order for example?

### ISSUE THREAD

**Issue by thiagobarrosrj** [bgmulinari/B1SLayer#35]
How can I cancel a sales order for example?

Eu não encontrei no B1SLayer uma chamada para cancelar um documento. Como faço isso usando o B1SLayer?

It would be to call the post below.

POST https://localhost:50000/b1s/v1/Orders(123)/Cancel

**Comment by bgmulinari** [comment]
Olá, @thiagobarrosrj.

A requisição abaixo deve fazer o cancelamento:

````c#
await serviceLayer.Request("Orders(123)/Cancel").PostAsync();
````

**Comment by GustavoArriola** [comment]
Hi @bgmulinari !

Do you think we can use that sintax in order to call a view?

`await serviceLayer.Request($"view.svc/{viewName}").GetAsync<...>();`

Regards,
Gustavo
