### ISSUE TITLE
Documentation on SLRequest.GetAllAsync<T>

### ISSUE THREAD

**Issue by rcalv002** [bgmulinari/B1SLayer#43]
Hi, congrats on the library, you've put in a good amount of work into it. Personally I use the odata client generation approach but this is more flexibly as the contracts are written by the user.

I noticed that the SLRequest.GetSync<T> takes a parameter to unwrap value property, but the SLRequest.GetAllAsync<T> does not, and it forces the unwrap. Could you add this to the docs ? I spent sometime trying to figure out why some response objects were coming back null then I realized this one is unwrapping no matter what (which kind of makes sense since user doesnt need to manage links or tags)

**Comment by bgmulinari** [comment]
Hi, @rcalv002.

Thanks for your input on this, that's indeed an oversight on my part. I'll make sure to make this clear on the method XML comment and other mentions of it for the next release.

**Comment by bgmulinari** [comment]
This behavior was made clear in the documentation with version [1.3.1](https://github.com/bgmulinari/B1SLayer/releases/tag/1.3.1).

Thanks again, @rcalv002, for reporting this.
