### ISSUE TITLE
Patch Batch Request not remove items in a collection

### ISSUE THREAD

**Issue by mruiz-GIEG** [bgmulinari/B1SLayer#47]
Hello, I am using slBatchRequests PATCH, to eliminate some elements from the collection, it does not give an error but it does not make the change and this that I specify the WithReplaceCollectionsOnPatch extension, it should be noted that only in the Batch I present the problem because in PatchStringAsync it works fine, but Since there are several changes, that's why I want it to go in Batch.

The code

var req1 = new SLBatchRequest(
                HttpMethod.Patch, 
                "WHS1('BV-091')", 
                "{\"WHS2Collection\": [{ \"LineId\":1,\"U_Usuario\": \"manager\",\"U_DesUsuario\":\"manager\" }]}") 
                .WithReplaceCollectionsOnPatch()
                .WithReturnNoContent(); 

                HttpResponseMessage[] batchResult = await _serviceLayer                       
                .PostBatchAsync(req1);

thanks for the help, great library B1Slayer

**Comment by bgmulinari** [comment]
Hi, @mruiz-GIEG.

I did a quick test on the `Items` resource and I was not able to reproduce the issue. Here are my results:

The collection to be updated with a line removed:
![a1](https://github.com/bgmulinari/B1SLayer/assets/30354770/71691828-3762-432c-b926-bf8ed6097402)

My request:
```c#
var reqBody = new { ItemPreferredVendors = new[] { new { BPCode = "V10000" } } };

var req1 = new SLBatchRequest(HttpMethod.Patch, "Items('A00001')", reqBody)
    .WithReplaceCollectionsOnPatch()
    .WithReturnNoContent(); // not really necessary as PATCH requests don't return any content

HttpResponseMessage[] batchResult = await serviceLayer.PostBatchAsync(req1); // 204 response
```

The collection after the request above was made (line successfully removed):
![a2](https://github.com/bgmulinari/B1SLayer/assets/30354770/3e2f23d2-585e-49f7-99d9-a997ee3a7214)

Do you observe the same issue on other resources as well?

**Comment by mruiz-GIEG** [comment]
Not only do I have a problem with Batch, but PatchStringAsync works great, no way am I going to have to make several calls to the server, I'll tell you about any news, thanks

**Comment by mruiz-GIEG** [comment]
Not only do I have a problem with Batch, but PatchStringAsync works great, no way am I going to have to make several calls to the server, I'll tell you about any news, thanks

**Comment by bgmulinari** [comment]
@mruiz-GIEG, try sending the batch request through Postman ([like shown here](https://answers.sap.com/answers/418305/view.html)) and see if works. Remember to use the same parameters (B1S-ReplaceCollectionsOnPatch=true in the request header).

If you get the same issue, then I guess it could be a Service Layer bug and not something related to B1SLayer.

**Comment by mruiz-GIEG** [comment]
Hello @bgmulinari  , good morning, do the tests attached to the screens, first do a get to see how many records there are, then do the batch successfully and then do a get again and the element collection was successfully updated.

Note: It is a master data type user table.

Batch code:

--batch_36522ad7-fc75-4b56-8c71-56071383e77c
Content-Type: application/http 
Content-Transfer-Encoding:binary

PATCH /b1s/v1/WHS1('BV-091')

{"WHS2Collection": [
         {            
            "LineId": 4,
            "U_Usuario": "manager",
            "U_DesUsuario": "manager"
        }
    ]
}

--batch_36522ad7-fc75-4b56-8c71-56071383e77c--

<img width="630" alt="Get" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/4a5c40de-c7ee-4b36-a054-b298ca939c0f">
<img width="634" alt="batch" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/71d48043-daf3-4361-a683-ce0be03a3008">
<img width="638" alt="Get Next" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/a9f582bc-3131-438b-8946-7ef4861d5b1e">
<img width="636" alt="Headers" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/af7abb2d-e9c0-4cc1-aba3-37491352634d">

**Comment by mruiz-GIEG** [comment]
Hello @bgmulinari , good morning, I proceeded with the tests, I attached the screens, first I did a get to see how many records there are, then I did the batch successfully and then I did a get again and the element collection was successfully updated.

Note: It is a master data type user table.

Batch code:

--batch_36522ad7-fc75-4b56-8c71-56071383e77c
Content-Type: application/http 
Content-Transfer-Encoding:binary

PATCH /b1s/v1/WHS1('BV-091')

{"WHS2Collection": [
         {            
            "LineId": 4,
            "U_Usuario": "manager",
            "U_DesUsuario": "manager"
        }
    ]
}

--batch_36522ad7-fc75-4b56-8c71-56071383e77c--

<img width="630" alt="Get" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/48bc021a-4bfd-4473-ac40-25608f4e4592">
<img width="634" alt="batch" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/aabd633a-7471-4c8d-9266-cb14ef3b71d1">
<img width="636" alt="Headers" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/a9e99876-9d3c-4030-ac6c-c2c274f701d3">
<img width="638" alt="Get Next" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/9669e1d5-aed3-420e-a34b-2478905dc91f">

**Comment by bgmulinari** [comment]
@mruiz-GIEG, I see that you put your `B1S-ReplaceCollectionsOnPatch=true` header in the main request, that's not what B1SLayer does. The header is put in the inner request inside your batch request body.

Can you test it again like this?

![image](https://github.com/bgmulinari/B1SLayer/assets/30354770/63378eb2-38ed-42a0-80f8-b04ae8739638)

```
--25f775be-0f5a-4bb0-bbd4-0b239a9b5eff
Content-Type: multipart/mixed; boundary="changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577"

--changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577
Content-Type: application/http; msgtype=request
content-transfer-encoding: binary

PATCH /b1s/v1/Items('A00001') HTTP/1.1
Host: 192.168.18.2:50000
B1S-ReplaceCollectionsOnPatch: true
Prefer: return-no-content
Content-Type: application/json; charset=utf-8

{"ItemPreferredVendors":[{"BPCode":"V10000"}]}
--changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577--

--25f775be-0f5a-4bb0-bbd4-0b239a9b5eff--
```

**Comment by mruiz-GIEG** [comment]
I tried with the code provided from postam, and it works correctly, I batch successfully and update the values, then I modify it for my user table and it gives ok without errors, but it does not update the data collection, unless I add in the header B1S-ReplaceCollectionsOnPatch to true, then I can come to the conclusion that if the sap system table works fine from B1SLayer, the batch does it satisfactorily including the ReplaceCollectionsOnPatch in each request, but if it is the user table it must go in the global header otherwise the request does not update the collection.

I attach the code:
Code with system tables:
--25f775be-0f5a-4bb0-bbd4-0b239a9b5eff
Content-Type: multipart/mixed; boundary="changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577"

--changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577
Content-Type: application/http; msgtype=request
content-transfer-encoding: binary

PATCH /b1s/v1/Items('AF02-000087') HTTP/1.1
Host: 192.168.0.243:50000
B1S-ReplaceCollectionsOnPatch: true
Prefer: return-no-content
Content-Type: application/json; charset=utf-8

{"ItemPreferredVendors":[{"BPCode":"V10000"}]}
--changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577--

--25f775be-0f5a-4bb0-bbd4-0b239a9b5eff--

Code with user tables:
--changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577
Content-Type: application/http; msgtype=request
content-transfer-encoding: binary

PATCH /b1s/v1/WHS1('BV-091') HTTP/1.1
Host: 192.168.0.243:50000
B1S-ReplaceCollectionsOnPatch: true
Prefer: return-no-content
Content-Type: application/json; charset=utf-8

{"WHS2Collection": [
         {            
            "LineId": 4,
            "U_Usuario": "manager",
            "U_DesUsuario": "manager"
        }
    ]
}
--changeset_a02032b8-d3eb-4d8b-94b2-f5d72a467577--

<img width="620" alt="Get" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/dddb42be-ff5b-4555-af31-e38482d32aa6">
<img width="637" alt="Headers" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/044af692-f6cc-4b1d-80bb-2a57323d1c8a">
<img width="629" alt="batch" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/e4a445a8-4859-4b11-a9a3-bfefd9086376">
<img width="629" alt="Get Next" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/1e0c5d3f-0d63-4226-adff-e31b2d91a2e1">

**Comment by mruiz-GIEG** [comment]
<img width="641" alt="Get Next" src="https://github.com/bgmulinari/B1SLayer/assets/61253953/662e6d14-6ca7-4397-a21e-86b048c5842e">

**Comment by bgmulinari** [comment]
@mruiz-GIEG, I tested it again with an UDO this time (master data type) and it still worked as expected, both on Postman and on B1SLayer. Are you able to test it in a different SAP environment to check if you get a different result?

GET request before PATCH:
![image](https://github.com/bgmulinari/B1SLayer/assets/30354770/4eff347d-1286-423a-8e2d-68f1658ad685)

PATCH request within a batch:
```c#
string reqBody = "{\"UDOTestLinesCollection\":[{\"Code\":\"UDO_Record1\",\"U_LineDesc\":\"Line1\",\"LineId\":1}]}";
var req1 = new SLBatchRequest(HttpMethod.Patch, "UDOTest('UDO_Record1')", reqBody).WithReplaceCollectionsOnPatch();
HttpResponseMessage[] batchResult = await serviceLayer.PostBatchAsync(req1);
```

PATCH request above captured in Fiddler Classic (monitoring tool):
```
--40a099f9-0f2d-4a20-bc15-820b07bb6a91
Content-Type: multipart/mixed; boundary="changeset_8dc20042-49fe-43f9-b476-92a724a05408"

--changeset_8dc20042-49fe-43f9-b476-92a724a05408
Content-Type: application/http; msgtype=request
content-transfer-encoding: binary

PATCH /b1s/v1/UDOTest('UDO_Record1') HTTP/1.1
Host: 192.168.18.2:50000
B1S-ReplaceCollectionsOnPatch: true
Content-Type: application/json; charset=utf-8

{"UDOTestLinesCollection":[{"Code":"UDO_Record1","U_LineDesc":"Line1","LineId":1}]}
--changeset_8dc20042-49fe-43f9-b476-92a724a05408--

--40a099f9-0f2d-4a20-bc15-820b07bb6a91--
```

GET request after PATCH (line successfully removed):
![image](https://github.com/bgmulinari/B1SLayer/assets/30354770/4d36fdc9-3a83-4ee2-adf1-a100b4df7477)

**Comment by mruiz-GIEG** [comment]
I tried with another udo that I have but with the same result, excuse my ignorance, modify the B1SLayer library, and add B1S-ReplaceCollectionsOnPatch in the general request and it works fine for me, I ask if I leave it like this, that can impact me in something negative, or It will be a version issue, the one I have is Sap Bussiones One 9.2 PL:08 (64 bits), I would not want to be modifying the library because when there is an update I would not like to lose the changes I make, what version of sap do you have.

**Comment by bgmulinari** [comment]
@mruiz-GIEG, that version was released quite a while ago, so it's very much possible this is an issue that was fixed in later releases. I'm on version 10.0 FP2208.

Can you try one last test? Try changing your Service Layer URL in your `SLConnection` instance from `/b1s/v1` to `/b1s/v2`. This will use OData v4 and could result in a different outcome.

**Comment by bgmulinari** [comment]
@mruiz-GIEG, were you able to perform the test?

**Comment by mruiz-GIEG** [comment]
@bgmulinari , Good morning, yes, I did the tests without success, we are evaluating how to migrate to version 10 next year, thank you very much.

**Comment by mruiz-GIEG** [comment]
@bgmulinari , Excellent news with Version 1.3.2, the problem has been solved, thank you very much.
