### ISSUE TITLE
Response body with post request

### ISSUE THREAD

**Issue by it-AhmedTaha** [bgmulinari/B1SLayer#48]
Hello, is there a way to get the response of successful post request and return it to the client? 
For example this request:
` await serviceLayer.Request("Invoices").PostAsync(arReserve);
`
Typically, when performing a successful POST request, a response containing information about the created invoice is returned.

**Comment by bgmulinari** [comment]
Hi, @it-AhmedTaha. Yes, here's the example from the README.md:

```c#
// Performs a POST on /Orders with the provided object as the JSON body, 
// creating a new order and deserializing the created order in a custom model class
var createdOrder = await serviceLayer.Request("Orders").PostAsync<MyOrderModel>(myNewOrderObject);
```

**Comment by trrytch** [comment]
Hi @bgmulinari, I noticed that it's not possible to do the same for a Patch request, is there a way of knowing that the PatchAsync request was successful?
