### ISSUE TITLE
How would you do an SQL query?

### ISSUE THREAD

**Issue by Tdue21** [bgmulinari/B1SLayer#5]
Stumbled upon this project by chance, and fell instantly in love. So much easier than that cumbersome OData client. 
Ran into an issue, which I need a bit of help with. 

How would you do an SQL query with this project? 
As far as I can tell, the only way I could do it, is: 
```cs
 var result = await Client.Request("SQLQueries('ItemPrices')/List")
                                     .SetQueryParam("itemCode", itemCode)
                                     .GetAsync<QueryResult<ItemPrice>>();
```

Where ItemPrices is, of course, the name of the query. 

Oh, QueryResult has been defined like this: 

```cs
public class QueryResult<T>
{
    public string SqlText { get; set; }
    public T[] Values { get; set; }
}
```

And, of course, ItemPrice is a class that reflects the fields being queried.

**Comment by bgmulinari** [comment]
Hi, I'd be glad to help. Unfortunately I'm not too familiar with the "SQLQueries" resource as it's a relatively new addition to Service Layer. However, if you could show me how you would perform such request in Postman, for instance, and what is returned JSON, maybe I can show you how to do it in B1SLayer.

**Comment by bgmulinari** [comment]
Hey, I took a better look at the "SQLQueries" resource and I think I get it. The thing to keep in mind is that B1SLayer will automatically unwrap the response whenever the JSON result is a collection, this means you don't need a model class containing the "values" array. If you don't want this behaviour, you can simply pass false in the optional parameter called "unwrapCollection" in the Get methods. With that in mind, here's how I'd do it in B1SLayer:

Let's assume I have a SQL Query that looks like this:
````
{
    "odata.metadata": "https://localhost:50000/b1s/v1/$metadata#SQLQueries/@Element",
    "odata.etag": "W/\"356A192B7913B04C54574D18C28D46E6395428AB\"",
    "SqlCode": "sql05",
    "SqlName": "queryOnItem",
    "SqlText": "select \"ItemCode\", \"ItemName\", \"ItmsGrpCod\" from \"OITM\" where \"ItemCode\" = :itemCode",
    "ParamList": "itemCode",
    "CreateDate": "2022-02-02",
    "UpdateDate": "2022-02-02"
}
````

To perform the request using B1SLayer, it would be something like this:
````c#
var items = await serviceLayer.Request("SQLQueries('sql05')/List")
    .SetQueryParam("itemCode", "'IT0001'") // Note the single quotes needed whenever the parameter is a string
    .GetAsync<ItemModel[]>();
````

My ItemModel class looks like this:
````c#
public class ItemModel
{
    public string ItemCode { get; set; }
    public string ItemName { get; set; }
    public int ItmsGrpCod { get; set; }
}
````

This will result in a GET request that looks like this:

`https://localhost:50000/b1s/v1/SQLQueries('sql05')/List?itemCode='IT0001'`

So, back to your code, I believe this would work:

````c#
var result = await Client.Request("SQLQueries('ItemPrices')/List")
  .SetQueryParam("itemCode", $"'{itemCode}'")
  .GetAsync<ItemPrice[]>();
````

Let me know if you still need help.

**Comment by Tdue21** [comment]
Ok cool. That makes sense. 
How would you create the query in the first place? 
Just a PostAsync with an anonymous class with the query data as argument?

Like this: 
```cs
await Client.Request("SQLQueries")
      .PostAsync<SqlQuery>(new
                 {
                     SqlCode = "ItemPrices",
                     SqlName = "A list of item prices",
                     SqlText =
                         "SELECT PriceList, Price, Currency, Factor, PriceType FROM ITM1 WHERE ItemCode=:itemCode",
                     ParamList = "itemCode"
                 });
```

**Comment by bgmulinari** [comment]
Yes, pretty much. It's your choice whether to use an anonymous type object or a normal object. I generally use anonymous objects when it's some simple routine that's executed only in a single place so I don't need to create a model class just for that.

In your case you seem to already have a model class called SQLQuery, so it might make more sense to create an instance of it instead of an anonymous object. But again, your choice.

Also, when you perform a Post and specify a class, like in your case `PostAsync<SqlQuery>`, this means the created entity will be deserialized into an object of this type, because by default, Service Layer returns the entity you just created whenever you create one. If you don't have a use for this created entity, you can do something like this and have better performance on your request:

````c#
await sl.Request("SQLQueries")
    .WithReturnNoContent()
    .PostAsync(new
    {
        SqlCode = "ItemPrices",
        SqlName = "A list of item prices",
        SqlText = "SELECT PriceList, Price, Currency, Factor, PriceType FROM ITM1 WHERE ItemCode=:itemCode",
        ParamList = "itemCode"
    });
````

**Comment by Tdue21** [comment]
Awesome, thank you for your quick response and help. It turns out I am having trouble getting my test installation of service layer to play, but that is an entirely different issue and nothing to do with this. 

Again, thank you for your library and time.
