### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by julio-prezero** [bgmulinari/B1SLayer#52]
How can I set a local certificate file to the requests?

**Comment by bgmulinari** [comment]
Hi, @julio-prezero.

Unfortunately, setting a client certificate is not possible as of now. It's definitely something on the list of possible improvements for version 2.0.

**Comment by julio-prezero** [comment]
Hi Bruno. Thank you for your prompt response. Enabling certificates would be great. Is it possible to add runtime entries to the http request's header section? Like a cookie with a Session ID so that the SAP B1 service could be authenticated?

Regards!

**Comment by bgmulinari** [comment]
@julio-prezero, Service Layer's authentication is already taken care of automatically by B1SLayer. The login is performed whenever necessary and the required session cookies are always sent in your requests. If you wish to add additional entries to the request headers, you can use the `WithHeader` extension method.

The `SLRequest` class [has a number of extension methods](https://github.com/bgmulinari/B1SLayer/blob/master/B1SLayer/SLRequestExtensions.cs) that can help you configure your request.

I recommend checking the [README](https://github.com/bgmulinari/B1SLayer/blob/master/README.md) and [my blog post](https://blogs.sap.com/2022/05/23/b1slayer-a-clean-and-easy-way-to-consume-sap-business-one-service-layer-with-.net/) for more info on B1SLayer's usage.

**Comment by bgmulinari** [comment]
@julio-prezero, I'm closing this issue for now but this is something I may revisit in the future. For now I've decided to not implement support for client certificates.

If anyone else is interested in this improvement, we can resume the discussion on the best approach.
