### ISSUE TITLE
On posting data with no data

### ISSUE THREAD

**Issue by sandy5791** [bgmulinari/B1SLayer#59]
hi ,
 I am send the request from SLbatchrequest  with ProductionOrders(123)/Cancel  this is Post Method But with no content i.e data = null and i am always getting bad format as a response

**Comment by bgmulinari** [comment]
Hi, @sandy5791. I've seen this before and for some reason, requests within a batch require a body, even if an empty one.

Try sending `"{}"` as the request body and it should work.

**Comment by sandy5791** [comment]
thank you it worked.
