### ISSUE TITLE
Error while posting attachment

### ISSUE THREAD

**Issue by chmsajid7** [bgmulinari/B1SLayer#6]
Hello guys,
I am continuously getting an error, so any kind of help will be highly appreciated. 
I am sending file to PostAttachmentAsync end point but I receive an exception; 
-- error code 404
-- error message Could not process request (Create File Error: C:\tmp) (Call failed. Error while copying content to a stream: POST https://xxxxxxxxxxxxxxxx:xxxx/b1s/v1/Attachments2)

Thanks You.

**Comment by bgmulinari** [comment]
Hi. Could you please provide more details? If you could share the part of your code where the error occurs, that would be helpful. Also are you on SQL Server or HANA?

**Comment by muhammadsajid1997** [comment]
I issue was resolved. The issue was that I didn't had right permissions in source path or Temp folder.

**Comment by bgmulinari** [comment]
That's good to hear. I'll be closing the issue but feel free to reopen it if you encounter any problem.
