### ISSUE TITLE
Flurl dependency for native system.text.json

### ISSUE THREAD

**Issue by rcalv002** [bgmulinari/B1SLayer#60]
Hello!

I see b1slayer is still using 3.2.4. Flurl has released v4 which should support system.text.json so we can move away from newtonsoft dependency in our net projects. Any chance you can check that out?

**Comment by bgmulinari** [comment]
Hi, @rcalv002.

The implementation of Flurl 4.0.0 was already started in the branch 2.0.0 for B1SLayer, but it's still a work in progress.

Flurl 4.0.0 introduced a lot of breaking changes and that will probably mean some breaking changes for B1SLayer 2.0.0 when it's eventually released.

**Comment by brakim** [comment]
@bgmulinari what is status on 2.0.0 need any help with testing/development?

**Comment by bgmulinari** [comment]
It's here, at last.

For now it's a prerelease because of the huge changes, so if you can test it and report back, I would really appreciate it.

Download it here: https://www.nuget.org/packages/B1SLayer/2.0.0-pre1
