### ISSUE TITLE
wanna as seranrio

### ISSUE THREAD

**Issue by sandy5791** [bgmulinari/B1SLayer#61]
hi,
you have done great work 
thank you.

I wanna Ask About the controlees on b1slayer batch transaction  
what if i want that if i am sending 10 batches and if 1 fails then my other data posts and failed one gives me response .
how many ways i can control and pls give me some type of documentation if possible.

thank you.

**Comment by bgmulinari** [comment]
Hi, @sandy5791.

I'm not sure I understand your question. Please refer to the [official Service Layer documentation regarding batch operations](https://help.sap.com/doc/6ab840ef2e8140f3af9eeb7d8fef9f06/10.0/en-US/Working_with_SAP_Business_One_Service_Layer.pdf#page=82).

**Comment by bgmulinari** [comment]
@sandy5791, I'm closing this issue. Let me know if you still need assistance.
