### ISSUE TITLE
SpecialPrices Request with Composite Key

### ISSUE THREAD

**Issue by flo-p** [bgmulinari/B1SLayer#62]
Hi, 

is there a Solution for the SpecialPrice Endpoint wich is using a composite key. 

I didn't manage to get this working:

serviceLayer.Request("SpecialPrices", "CardCode='81389',ItemCode = '48000-059'").GetAsync();

kind regards 

Flo

**Comment by joaoantoniomartinsfilho** [comment]
Hey @flo-p how's it going? 

Could you try something like this, please?

`
await serviceLayer.Request("SpecialPrices(CardCode='81389',ItemCode = '48000-059')).GetAsync();
`

Maybe the issue helps you: #53

**Comment by flo-p** [comment]
Hi @joaoantoniomartinsfilho 

thank you very much, this worked for me: 

var sp = await serviceLayer.Request($"SpecialPrices(CardCode = '81389', ItemCode = '48000-059')").GetAsync();
