### ISSUE TITLE
Logged in but keep getting "Authorization header not found"?

### ISSUE THREAD

**Issue by KwokHoiMan** [bgmulinari/B1SLayer#65]
After logging on, the callback shows that the session is established, but on the next request the response is "authorisation header not found".

This repeats until the .NET console program crashes. 

![image](https://github.com/bgmulinari/B1SLayer/assets/24966628/a300237f-935d-4598-83b9-87e668f0b5e7)

I am using SAP v10 SP2311 64-bit.

Any advice appreciated!

**Comment by bgmulinari** [comment]
Hi, @KwokHoiMan. Can you share a the code snippet that reproduces your problem, please?

**Comment by Shield1739** [comment]
In case anyone comes up with this error, the problems comes from including the /Login in the service layer root uri

Example:

This is **WRONG**:
`new SLConnection("https://sapserver:50000/b1s/v1/Login", "CompanyDB", "manager", "12345");`

This is **CORRECT**:
`new SLConnection("https://sapserver:50000/b1s/v1", "CompanyDB", "manager", "12345");`

**Comment by bgmulinari** [comment]
@KwokHoiMan, I'm closing this issue. Let me know if you still need assistance.
