### ISSUE TITLE
Logout is not working

### ISSUE THREAD

**Issue by ByYogi** [bgmulinari/B1SLayer#66]
In the screenshot, I logged out but was still able to request B1SLayer
![image](https://github.com/bgmulinari/B1SLayer/assets/111735598/ece53783-d2b4-4a75-af37-cfa0b2e9fb18)

**Comment by ByYogi** [comment]
Each request `ServiceLayer` will check the login status and if it has been more than 30 minutes since the last login, it will automatically call the `Login` request and save the login cookies.
`LogoutAsync` will call the `Logout` request and clear the cookie, as well as clear the last login time. So the next time the `ServiceLayer` checks for more than 30 minutes since the last login, it will automatically login again.

**Comment by bgmulinari** [comment]
Hi, @ByYogi. That's correct.

B1SLayer has an auto login logic that will perform a login (if you don't have an active session) every time you perform a request. So when you logout and immediately perform another request, a new login request will be made in the background before it.
