### ISSUE TITLE
I am having problems with PostBatchAsync batch updates:   should be two '\r\n' between sub-request

### ISSUE THREAD

**Issue by ByYogi** [bgmulinari/B1SLayer#68]
"Incomplete request, Please check if the sub-request has complete request content and there should be two '\r\n' between sub-request header and content!"

```CSharp
using B1SLayer;
var serviceLayer = new SLConnection("https://***:10000/b1s/v2", "***", "***", "***");

List<SLBatchRequest> batchReq = new List<SLBatchRequest>();

batchReq.Add(new SLBatchRequest(new HttpMethod("Patch"), $"Items('{"$creation"}')", new
{
    ItemCode = "$creation",
    ItemName = "Test Item1"
})); batchReq.Add(new SLBatchRequest(new HttpMethod("Patch"), $"Items('{"$creation2"}')", new
{
    ItemCode = "$creation2",
    ItemName = "Test Item2"
}));
HttpResponseMessage[] batchResult = await serviceLayer.PostBatchAsync(batchReq);

```

**Comment by ByYogi** [comment]
I also get an error when I use the README example.
```
B1SLayer.SLException: 'Content ID should be specified in each change set request.'
```

![image](https://github.com/bgmulinari/B1SLayer/assets/111735598/ea348329-4e1c-49ab-bd20-934f24f73e92)
![image](https://github.com/bgmulinari/B1SLayer/assets/111735598/e19275ab-6052-4c7d-bc17-08415382d609)

**Comment by bgmulinari** [comment]
Hi, @ByYogi.

When using OData V4 protocol (indicated by the 'v2' in your Service Layer URL), you are required to specify the content ID in all requests within a batch, even if you don't use it. [Check the Service Layer User Manual regarding this topic](https://help.sap.com/doc/6ab840ef2e8140f3af9eeb7d8fef9f06/10.0/en-US/Working_with_SAP_Business_One_Service_Layer.pdf#page=84).

Try changing your URL to 'v1' or specify the content ID in each request object (optional constructor parameter for the _SLBatchRequest_ class).
