### ISSUE TITLE
Multiple Company DI Connection Dictionary 

### ISSUE THREAD

**Issue by matheusfellipe** [bgmulinari/B1SLayer#69]
I'm getting DI error using the connection dictionary in service collection extensions method, like

     public static IServiceCollection AddB1SLayer(this IServiceCollection services, IConfiguration configuration)
     {
       

         services.AddSingleton(serviceLayer => 
         new Dictionary<string,SLConnection>()
         {
             { "foo", new SLConnection(configuration["Url"], "companyDb", configuration["UserName"],  configuration["PassWord"]) },
              { "boo", new SLConnection(configuration["Url"],  "companyDb", configuration["UserName"],  configuration["PassWord"]) }

         });

         return services;
     }
 }

**Comment by EricWu91** [comment]
Hi! What's the error?

**Comment by matheusfellipe** [comment]
I was injecting SLConnection rather than the dictionary
