### ISSUE TITLE
Unable to filter attachment using file name

### ISSUE THREAD

**Issue by muhammadsajid1997** [bgmulinari/B1SLayer#7]
Hello there,
I wanted to filter out the attachment using file name, but I am unable top do so.
Any kind of help would be appreciated.

**Comment by bgmulinari** [comment]
Hello. You are able to filter by the file name, however you still need to provide the attachment entry (AbsEntry). Keep in mind a single attachment entry can be composed by multiple files (attachment lines).

So, if you need to get a specific file by name of a given attachment entry, this is how to do it:

````c#
var sl = new SLConnection("https://localhost:50000/b1s/v1", "SBO_COMPANYDB", "manager", "12345");
var attachment = await sl.GetAttachmentAsBytesAsync(120, "myfile.pdf");
````

In the example above, you obtain a file named "myfile.pdf" for the attachment entry with number 120.

**Comment by muhammadsajid1997** [comment]
@bgmulinari 
I am posting an attachment which throughs an error "A file with this name already exists". I want to overwrite the file if already exists. So to overwrite the file I have to call a patch request, but I do not have the attachment entry of the existing file to call the patch request.

**Comment by bgmulinari** [comment]
Unfortunately I don't think you'll be able to do that natively. An alternative would be to develop a custom view that returns what you need and then expose it on Service Layer.

**Comment by muhammadsajid1997** [comment]
Ok Thanks. That was really helpful
