### ISSUE TITLE
Call timed out: POST https://xxx.xxx.net:50000/b1s/v1/Login With Initial call

### ISSUE THREAD

**Issue by johandantuma** [bgmulinari/B1SLayer#72]
I'm experiencing a stang issue with regards to the login part of the B1Slayer. When running the first instance of a API BO of B1Slayer the connection times out. 

When retrying it if work without any problems. When the connection timers out after 30 of if i recompile my C# project and rerun it also times out.

**Comment by bgmulinari** [comment]
Hi @johandantuma.

Can you provide more information regarding your scenario and maybe provide a code snippet that reproduces your issue?

Do you observe the same issue when logging in through Postman, for instance?

**Comment by johandantuma** [comment]
Hi Bruno


The issue doesn’t arise when using postman

The connection service layer

    public sealed  class ServiceLayer
    {


        private static readonly SLConnection _serviceLayer = new SLConnection(
             https://nuvo.seidorcloud.net:50000/b1s/v1/,
            "UAT_TRAININGDB", "Rcsys", ***@***.***!");

        static ServiceLayer() { }

        private ServiceLayer() { }


        public static SLConnection Connection => _serviceLayer;





    }


One of my calls to the API

var v = await ServiceLayer.Connection

                        .Request("$crossjoin(BusinessPartners,PaymentTermsTypes)")
                        .WithTimeout(240)
                        .Expand("BusinessPartners($select=CardCode,CardName,Notes),PaymentTermsTypes($select=CreditLimit,PaymentTermsGroupName)")
                        .Filter("BusinessPartners/PayTermsGrpCode eq PaymentTermsTypes/GroupNumber and CardType eq 'C'")
                        .WithPageSize(0)

                        .GetStringAsync();

**Comment by bgmulinari** [comment]
@johandantuma, I see that you are setting the page size to zero, which means you are trying to obtain all records in the database in a single request. Depending on the number of records to retrieve, this could take a long time and therefore could be te reason for the timeout you are experiencing.

If you wish to retrieve all records, I recommend using the `GetAllAsync` request method. This will loop through all pages for you until all records are retrieved. For this you will need to define a model class for the object, as `GetAllAsync` returns a list of said object type.

**Comment by johandantuma** [comment]
Hi Bruno

I see what you’re getting at but as a test I’ve just done a basic Login using

***@***.***

And I’m still getting a timeout

***@***.***

**Comment by bgmulinari** [comment]
@johandantuma, I'm closing this issue. Let me know if you still need assistance.
