### ISSUE TITLE
Enriching SLException with HTTP error data

### ISSUE THREAD

**Issue by EricWu91** [bgmulinari/B1SLayer#73]
Hi, Bruno.

Can I suggest that SLException be enriched with HTTP error data?
I'd like to know things like the status code, and the received body. 

I know these data are provided by the `FlurlHttpException`. Can I create a PR with the suggested changes?

**Comment by bgmulinari** [comment]
Hi, @EricWu91.

With the current implementation, the `InnerException` of a `SLException` will always be a `FlurlHttpException`. Do you have something different in mind?
