### ISSUE TITLE
Specifying custom headers on SLConnection

### ISSUE THREAD

**Issue by EricWu91** [bgmulinari/B1SLayer#74]
Sorry for the barrage of questions :)

As specified here (https://community.sap.com/t5/enterprise-resource-planning-q-a/service-layer-how-to-remove-all-addresses-of-a-business-partner/qaq-p/578058), whenever I want to clear the collections of a PATCH request (e.g. Business Partners' addresses), I'm required to provide a specific header: B1S-ReplaceCollectionsOnPatch=true

Is there a way to do that in SLConnection?

**Comment by bgmulinari** [comment]
Not really, I'm yet to write a proper documentation for B1SLayer. I'll start that once 2.0 is out :)

**Comment by EricWu91** [comment]
Ok! If you need, I can help you with that. 
Just create an issue and mention me and I'll do what I can.

**Comment by bgmulinari** [comment]
@EricWu91, I'm closing this issue. Let me know if you still need assistance.
