### ISSUE TITLE
Best way o check if item exist

### ISSUE THREAD

**Issue by CribAd** [bgmulinari/B1SLayer#76]
Hi all,

Nice library, thanks!

I want to check if an Item with a specific ItemCode exists in SAP B1. 

I do https://[servicelayer]/b1s/v1/Items('12345')?$select=ItemCode. When ItemCode 12345 exists, I will get a successful response. But when it does not exist I get an unhandled exception. Of course I can resolve this with a try-catch, but that doesn't sound like the most smooth way to check if a specific item exists. What is your advise?

**Comment by jmartins-sh** [comment]
Hey @CribAd how's it going? Hope well! 

Actually you problably got a 404 status codes, which will thrown an exception. If you like you can modify this behavior during the request using the extension method called `.AllowHttpStatus(statusCode)`, in your case 404. 

` cs       public static SLRequest AllowHttpStatus(this SLRequest request, params HttpStatusCode[] statusCodes) `

**Comment by CribAd** [comment]
Thanks, that works.

**Comment by bgmulinari** [comment]
Thanks for your help, @jmartins-sh.
