### ISSUE TITLE
I Would like to be able to customize the InternalLogin timeout period

### ISSUE THREAD

**Issue by ByYogi** [bgmulinari/B1SLayer#78]
The default timeout for internal login is 3s, which is not appropriate in some places and often results in a timeout error. But I didn't find any place to set the timeout for internal login.

**Comment by bgmulinari** [comment]
Hi, @ByYogi.

B1SLayer does not specify a timeout value for the login request. Therefore, it should use the [default 100 seconds for the HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-8.0#remarks).

Where did you get this 3s value from?

**Comment by ByYogi** [comment]
> Hi, @ByYogi.
> 
> B1SLayer does not specify a timeout value for the login request. Therefore, it should use the [default 100 seconds for the HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-8.0#remarks).
> 
> Where did you get this 3s value from?

I got 3s value from my error log
Finally, I modified the source code to add WithTimout solution
![image](https://github.com/user-attachments/assets/77095f8e-ac51-41ca-832c-7ec3d2304bf8)

**Comment by ByYogi** [comment]
Hi @bgmulinari  
Thank you for responding so positively.
I think it might be possible to solve this problem in other ways. Instead of `WithTimeout`?

This is B1SL responsed timout error:
``` html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> 
<html>
   <head>
      <title>502 Proxy Error</title>
   </head>
   <body>
      <h1>Proxy Error</h1>
      <p>The proxy server received an invalid  response from an upstream server.<br />  The proxy server could not handle the request
      <p>Reason: <strong>Error reading from remote server</strong></p>
      </p> 
   </body>
</html>
```
![image](https://github.com/user-attachments/assets/32d2ecac-136b-4a4f-9928-51297f00476e)

**Comment by bgmulinari** [comment]
@ByYogi, the HTTP error `502 Bad Gateway` is not a timeout error.

This indicates something wrong on the server side. I recommend you check your server and Service Layer installation, or even contacting SAP support.

I don't believe this issue is related to B1SLayer.

**Comment by ByYogi** [comment]
ok
