### ISSUE TITLE
How to call a calculation view

### ISSUE THREAD

**Issue by John-Ehv** [bgmulinari/B1SLayer#83]
I have to call a calculation view with B1SLayer.
Now GET https://10.0.0.0:50000/b1s/v1/sml.svc/NettoTestQueryParameters(P_CustomerNo='007790', P_fromDate='2023-01-01',P_toDate='2024-12-31')/NettoTestQuery

I have tried different ways to da this with B1SLayer, but not one is working.
Can anyone help me?

Thank you.

**Comment by bgmulinari** [comment]
Hi, @John-Ehv.

In this case, I believe you can perform the request like this:

```c#
var result = await serviceLayer
    .Request("sml.svc/NettoTestQueryParameters(P_CustomerNo='007790', P_fromDate='2023-01-01',P_toDate='2024-12-31')/NettoTestQuery")
    .GetAsync<YourModelType>();
```

It's a bit similar to the `SQLQueries` resource, demonstrated in #5. Let me know if it works.

**Comment by John-Ehv** [comment]
Hi,

Thank you.
This work perfectly.
